{
 "title": "Kafka Overview",
 "description": "Kafka usage and throughput",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Job", "query": "label_values(job)" },
   {
    "name": "Topic",
    "query": "label_values(kafka_topic_partitions{job=\"[[Job]]\"}, topic)"
   },
   {
    "name": "ConsumerGroup",
    "query": "label_values(kafka_consumergroup_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"}, consumergroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "Brokers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_brokers{job=\"[[Job]]\"}"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{job=\"[[Job]]\",topic=\"[[Topic]]\"})"
    }
   ]
  },
  {
   "title": "Throughput In",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"}[5m]))",
     "legendFormat": "Messages In / sec"
    }
   ]
  },
  {
   "title": "Throughput Out",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\",consumergroup=\"[[ConsumerGroup]]\"}[5m]))",
     "legendFormat": "Messages Out / sec"
    }
   ]
  },
  {
   "title": "ConsumerGroup Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{job=\"[[Job]]\",topic=\"[[Topic]]\",consumergroup=\"[[ConsumerGroup]]\"})",
     "legendFormat": "ConsumerGroup lag"
    }
   ]
  },
  {
   "title": "ConsumerGroup Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\",consumergroup=\"[[ConsumerGroup]]\"})",
     "legendFormat": "ConsumerGroup offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"})",
     "legendFormat": "Topic offset"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Messages / sec" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_topic_partition_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"}[5m]))",
     "legendFormat": "Partition {{partition}}"
    },
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"}[5m]))",
     "legendFormat": "All partitions"
    }
   ]
  },
  {
   "title": "Messages Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Messages / sec" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_topic_partition_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"}[5m]))",
     "legendFormat": "Partition {{partition}}"
    },
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{job=\"[[Job]]\",topic=\"[[Topic]]\"}[5m]))",
     "legendFormat": "All partitions"
    }
   ]
  }
 ]
}