#!/bin/bash
zoo0=$1
zoo1=$2
zoo2=$3
until nc -z -v -w5 $zoo0 2181; do echo waiting for zookeeper; sleep 5; done;
until nc -z -v -w5 $zoo1 2181; do echo waiting for zookeeper; sleep 5; done;
until nc -z -v -w5 $zoo2 2181; do echo waiting for zookeeper; sleep 5; done;